name: Run unit tests
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: ./gradlew build shadowJar
      - uses: actions/upload-artifact@v2
        with:
          name: discop-worker-jar
          path: discop-worker/build/libs/discop-worker-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: discop-scheduler-jar
          path: discop-scheduler/build/libs/discop-scheduler-all.jar
