name: Run unit tests
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: ./gradlew build shadowJar
      - uses: actions/upload-artifact@v2
        with:
          name: discop-worker-jar
          path: discop-worker/build/libs/discop-worker-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: discop-scheduler-jar
          path: discop-scheduler/build/libs/discop-scheduler-all.jar

      # Build Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push latest Docker image for discop-scheduler
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.scheduler
          push: true
          tags: |
            ghcr.io/kateinoigakukun/discop-scheduler:latest
            ghcr.io/kateinoigakukun/discop-scheduler:${{ github.sha }}

      - name: Push latest Docker image for discop-worker
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.worker
          push: true
          tags: |
            ghcr.io/kateinoigakukun/discop-worker:latest
            ghcr.io/kateinoigakukun/discop-worker:${{ github.sha }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            discop-worker/build/libs/discop-worker-all.jar
            discop-scheduler/build/libs/discop-scheduler-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
